### ISSUE TITLE
팀 소개 페이지 오류

### ISSUE THREAD

**Issue by solsol0609** [konosuba-it/konosuba-it#3]
팀 소개 페이지(/team_intro)에서 로고를 클릭하면 아무런 반응이 없습니다.

해당 페이지에서 로고 클릭시 이동 할 수 있도록 패치해야 합니다.

**Comment by solsol0609** [comment]
추가적으로 깃허브 아이콘이 없습니다

**Comment by solsol0609** [comment]
이미지가 HTTPS 처리 되지 않아 팀 소개 페이지에 자물쇠 아이콘이 없습니다.

**Comment by gaon12** [comment]
6f6823b 패치
- [x] 로고 클릭시 메인 페이지로 이동
- [x] HTTPS 처리
- [ ] 깃허브 아이콘

**Comment by solsol0609** [comment]
통계 페이지(/stats)에서도 아이콘이 뜨지 않는 문제가 발생함.

uikit icon js를 로드하지 않아 발생하는 문제임

내일중으로 수정할게요

**Comment by solsol0609** [comment]
170314b90ea5cb3dcb71f81dd6e442065bcdcc5d 패치
- [x] 로고 클릭시 메인 페이지로 이동
- [x] HTTPS 처리
- [x] 깃허브 아이콘

이 이슈에 대한 모든 패치를 완료하였습니다.
